import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('champions').insert([
    {
      id: 1,
      name: 'Warrior',
      level: 1,
      xp_max: 1000,
      strength: 20,
      dexterity: 15,
      intelligence: 10,
      vitality: 25,
      money: 100,
      guildId: null,
      roleId: 1,
    },
    {
      id: 2,
      name: 'Mage',
      level: 1,
      xp_max: 1000,
      strength: 10,
      dexterity: 15,
      intelligence: 25,
      vitality: 15,
      money: 50,
      guildId: null, 
      roleId: 2,
    },
    {
      id: 3,
      name: 'Rogue',
      level: 1,
      xp_max: 1000,
      strength: 15,
      dexterity: 25,
      intelligence: 10,
      vitality: 15,
      money: 75,
      guildId: null,
      roleId: 3,
    },
    {
      id: 4,
      name: 'Paladin',
      level: 1,
      xp_max: 1000,
      strength: 18,
      dexterity: 12,
      intelligence: 15,
      vitality: 20,
      money: 90,
      guildId: null,
      roleId: 4,
    },
    {
      id: 5,
      name: 'Druid',
      level: 1,
      xp_max: 1000,
      strength: 12,
      dexterity: 14,
      intelligence: 22,
      vitality: 18,
      money: 60,
      guildId: null,
      roleId: 5,
    },
  ]);
}
