import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {


	await knex('champions').insert([
		{
			userId: 1,
			name: 'Thorgar',
			level: 1,
			hp: 100,
			strength: 20,
			dexterity: 15,
			intelligence: 10,
			vitality: 25,
			money: Math.floor(Math.random() * 90000) + 10000,
			guildId: null,
			roleId: 1,
		},
		{
			userId: 2,
			name: 'Elandra',
			level: 1,
			hp: 100,
			strength: 10,
			dexterity: 15,
			intelligence: 25,
			vitality: 15,
			money: Math.floor(Math.random() * 90000) + 10000,
			guildId: null,
			roleId: 2,
		},
		{
			userId: 3,
			name: 'Kael',
			level: 1,
			hp: 100,
			strength: 15,
			dexterity: 25,
			intelligence: 10,
			vitality: 15,
			money: Math.floor(Math.random() * 90000) + 10000,
			guildId: null,
			roleId: 3,
		},
		{
			userId: 4,
			name: 'Seraphina',
			level: 1,
			hp: 100,
			strength: 18,
			dexterity: 12,
			intelligence: 15,
			vitality: 20,
			money: Math.floor(Math.random() * 90000) + 10000,
			guildId: null,
			roleId: 4,
		},
		{
			userId: 5,
			name: 'Faelar',
			level: 1,
			hp: 100,
			strength: 12,
			dexterity: 14,
			intelligence: 22,
			vitality: 18,
			money: Math.floor(Math.random() * 90000) + 10000,
			guildId: null,
			roleId: 5,
		},
	]);
}
